name: Find Lowest Number Automation
on: [push]
jobs: 
  find_lowest_number:
    name: Find Lowest Number
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"
    - name: Produce Lowest Number of 10 Numbers
      run: python3 find_lowest_number.py test_data/test1_input.txt test_data/test1_output.txt
      
    - name: Test1 - Display Lowest Number to Output File
      run: cat test_data/test1_output.txt

    - name: Test1 - Differecnes Between Output and Expected
      run: diff test_data/test1_output.txt test_data/test1_expected.txt

    - name: Test2 - Produce Number in File
      run: python3 find_lowest_number.py test_data/test2_input.txt test_data/test2_output.txt

    - name: Test2 - Differecnes Between Output and Expected
      run: diff test_data/test2_output.txt test_data/test2_expected.txt

    - name: Test3 - Produce No Number in File Text
      run: python3 find_lowest_number.py test_data/test3_input.txt test_data/test3_output.txt

    - name: Test3 - Differecnes Between Output and Expected
      run: diff test_data/test3_output.txt test_data/test3_expected.txt
